AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ContainerRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: listo
      LifecyclePolicy:
        LifecyclePolicyText: >
          {
            "rules": [
                {
                    "rulePriority": 1,
                    "description": "Keep only 10 images",
                    "selection": {
                        "tagStatus": "any",
                        "countType": "imageCountMoreThan",
                        "countNumber": 10
                    },
                    "action": {
                        "type": "expire"
                    }
                }
            ]
          }